services:
  app:
    image: kode-book
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    env_file:
      - .env
    ports:
      - "3000:3000"